name: 'Triage Review to Team'
description: 'Automatically request reviews from a team in an org'
inputs:
  github-token:
    description: 'Token to access github API with.'
    required: true
  label:
    description: 'Label to apply to issue.'
    default: 'Needs QA'
  organization:
    description: 'Organization to triage within.'
    default: 'panorama-ed'
  parent-team:
    description: 'The parent team to draw candidate teams from.'
    default: 'Engineering'
runs:
  using: 'node12'
  main: 'index.js'
